### PR TITLE
Makes grunt project sample vanilla js

### PR DESCRIPTION
**Pull request by MatthewVita**
this is kind of hard to test because things get overwritten, but it's a start.

### CODE REVIEW

**Comment by DavidSouther** [comment]
I really like what you've done here; I've taken the ideas and pulled them into https://github.com/RupertJS/rupert-grunt/pull/5

**Comment by MatthewVita** [comment]
Very nice! I love that we can have the best of both worlds, great idea. When this is finalized, which of the two tgz/zip do you think should be referenced on the main Rupert repo README?

**Comment by DavidSouther** [comment]
The `tgz`, it can be put in a shell pipeline. Both will have links, though.

**Comment by MatthewVita** [comment]
I mean't which example app will be referenced on the main Rupert repo... as in vanilla vs angular (tgz/zip)

**Pull request closed without merging**
